name: Build Flutter APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Generate Flutter Platform Code
        run: |
          mkdir -p backup_lib
          cp -r lib backup_lib/
          cp pubspec.yaml backup_pubspec.yaml
          mkdir -p backup_android
          cp android/app/src/main/AndroidManifest.xml backup_android/
          
          # Generate Android and iOS templates
          flutter create --platforms android .
          
          # Restore our custom code
          cp backup_pubspec.yaml pubspec.yaml
          cp -r backup_lib/* lib/
          cp -f backup_android/AndroidManifest.xml android/app/src/main/AndroidManifest.xml

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Release)
        run: flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SEETHA-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
